pact/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from text_app.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authorization/', include('authorization.urls')),
    path('student_cabinet/', include('student_cabinet.urls')),
    path('text/', include('text_app.urls')),
    path('', home_view, name='home'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

text_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Добавляем маршрут для отображения текста
    path('show_text/', views.show_text, name='show_text'),
    path('show_error_markup/', views.show_error_markup, name='show_error_markup'),
    path('show_text_markup/', views.show_text_markup, name='show_text_markup')
]

db_editor/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class CustomUserManager(BaseUserManager):
    def create_user(self, login, password=None, **extra_fields):
        """Создание и сохранение обычного пользователя"""
        if not login:
            raise ValueError('The Login field must be set')
        user = self.model(login=login, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, login, password=None, **extra_fields):
        """Создание и сохранение суперпользователя"""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(login, password, **extra_fields)

class Rights(models.Model):
    idrights = models.AutoField(primary_key=True)
    rightsname = models.CharField(max_length=100, unique=True)

    class Meta:
        db_table = 'tblrights'

    def __str__(self):
        return self.rightsname
    
class User(AbstractBaseUser, PermissionsMixin):
    iduser = models.AutoField(primary_key=True)
    login = models.CharField(max_length=100, unique=True)
    password = models.CharField(max_length=128)
    lastname = models.CharField(max_length=100)
    firstname = models.CharField(max_length=100)
    middlename = models.CharField(max_length=100, null=True, blank=True)
    birthdate = models.DateField(null=True, blank=True)
    gender = models.BooleanField(null=True, blank=True)  # 0 или 1
    idrights = models.ForeignKey(Rights, on_delete=models.CASCADE, db_column='idrights', default=1)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'login'
    REQUIRED_FIELDS = ['lastname', 'firstname']

    class Meta:
        db_table = 'tbluser'  

    def __str__(self):
        return self.login

class AcademicYear(models.Model):
    idayear = models.AutoField(primary_key=True) 
    title = models.CharField(max_length=10)

    class Meta:
        db_table = 'tblacademicyear'  

    def __str__(self):
        return self.title

class Emotion(models.Model):
    idemotion = models.AutoField(primary_key=True)  
    emotionname = models.CharField(max_length=100, unique=True)  

    class Meta:
        db_table = 'tblemotion' 

    def __str__(self):
        return self.emotionname  

class Error(models.Model):
    iderror = models.AutoField(primary_key=True)  
    correct = models.TextField(blank=True, null=True)  
    comment = models.TextField(blank=True, null=True) 
    changedate = models.DateField(blank=True, null=True)  
    iderrorlevel = models.ForeignKey('ErrorLevel', on_delete=models.CASCADE, blank=True, null=True, db_column='iderrorlevel')  
    idreason = models.ForeignKey('Reason', on_delete=models.CASCADE, blank=True, null=True, db_column='idreason')  
    iderrortag = models.ForeignKey('ErrorTag', on_delete=models.CASCADE, db_column='iderrortag')  

    class Meta:
        db_table = 'tblerror' 

    def __str__(self):
        return f"Error {self.iderror}"

class ErrorLevel(models.Model):
    iderrorlevel = models.AutoField(primary_key=True)
    errorlevelname = models.CharField(max_length=255)
    errorlevelabbrev = models.CharField(max_length=30, blank=True, null=True)
    errorlevelvalue = models.SmallIntegerField()

    class Meta:
        db_table = 'tblerrorlevel'

    def __str__(self):
        return self.errorlevelname
    
class ErrorTag(models.Model):
    iderrortag = models.AutoField(primary_key=True)
    tagtext = models.TextField()
    tagtextrussian = models.TextField()
    tagtextabbrev = models.TextField()
    tagcolor = models.CharField(max_length=7)
    idtagparent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, db_column='idtagparent')

    class Meta:
        db_table = 'tblerrortag'

    def __str__(self):
        return self.tagtext

class ErrorToken(models.Model):
    iderrortoken = models.AutoField(primary_key=True)
    position = models.IntegerField(blank=True, null=True)
    iderror = models.ForeignKey('Error', on_delete=models.CASCADE, db_column='iderror')
    idtoken = models.ForeignKey('Token', on_delete=models.CASCADE, db_column='idtoken')

    class Meta:
        db_table = 'tblerrortoken'

    def __str__(self):
        return f"ErrorToken {self.iderrortoken}"

class Group(models.Model):
    idgroup = models.AutoField(primary_key=True)
    groupname = models.CharField(max_length=10)
    studycourse = models.SmallIntegerField()
    idayear = models.ForeignKey('AcademicYear', on_delete=models.CASCADE, db_column='idayear')

    class Meta:
        db_table = 'tblgroup'

    def __str__(self):
        return self.groupname

class PosTag(models.Model):
    idpostag = models.AutoField(primary_key=True)
    tagtext = models.TextField()
    tagtextrussian = models.TextField()
    tagtextabbrev = models.TextField()
    tagcolor = models.CharField(max_length=7)

    class Meta:
        db_table = 'tblpostag'

    def __str__(self):
        return self.tagtext

class Reason(models.Model):
    idreason = models.AutoField(primary_key=True)
    reasonname = models.CharField(max_length=255)
    reasonabbrev = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        db_table = 'tblreason'

    def __str__(self):
        return self.reasonname
    
class Sentence(models.Model):
    idsentence = models.AutoField(primary_key=True)
    sentensetext = models.TextField()
    ordernumber = models.IntegerField()
    idtext = models.ForeignKey('Text', on_delete=models.CASCADE, db_column='idtext')

    class Meta:
        db_table = 'tblsentence'

    def __str__(self):
        return f"Sentence {self.idsentence} (Order: {self.ordernumber})"

class Student(models.Model):
    idstudent = models.AutoField(primary_key=True)
    idgroup = models.ForeignKey('Group', on_delete=models.CASCADE, db_column='idgroup')
    iduser = models.ForeignKey('User', on_delete=models.CASCADE, db_column='iduser')

    class Meta:
        db_table = 'tblstudent'

    def __str__(self):
        return f"Student {self.idstudent}"

class Text(models.Model):
    idtext = models.AutoField(primary_key=True)
    header = models.CharField(max_length=255)
    text = models.TextField()
    idstudent = models.ForeignKey('Student', on_delete=models.CASCADE, db_column='idstudent')
    createdate = models.DateField(null=True, blank=True)
    modifieddate = models.DateField(null=True, blank=True)
    educationlevel = models.IntegerField(null=True, blank=True)
    idtexttype = models.ForeignKey('TextType', on_delete=models.CASCADE, db_column='idtexttype', null=True, blank=True)
    idwriteplace = models.ForeignKey('WritePlace', on_delete=models.CASCADE, db_column='idwriteplace', null=True, blank=True)
    idwritetool = models.ForeignKey('WriteTool', on_delete=models.CASCADE, db_column='idwritetool', null=True, blank=True)
    idemotion = models.ForeignKey('Emotion', on_delete=models.CASCADE, db_column='idemotion', null=True, blank=True)
    textgrade = models.IntegerField(null=True, blank=True)
    completeness = models.IntegerField(null=True, blank=True)
    structure = models.IntegerField(null=True, blank=True)
    coherence = models.IntegerField(null=True, blank=True)
    selfrating = models.IntegerField(null=True, blank=True)
    selfassesment = models.IntegerField(null=True, blank=True)
    poscheckflag = models.BooleanField(null=True, blank=True)
    errorcheckflag = models.BooleanField(null=True, blank=True)
    poscheckdate = models.DateField(null=True, blank=True)
    errorcheckdate = models.DateField(null=True, blank=True)
    iduserteacher = models.ForeignKey('User', on_delete=models.CASCADE, db_column='iduserteacher', null=True, blank=True, related_name='teacher_texts')
    idusererrorcheck = models.ForeignKey('User', on_delete=models.CASCADE, db_column='idusererrorcheck', null=True, blank=True, related_name='errorcheck_texts')
    iduserposcheck = models.ForeignKey('User', on_delete=models.CASCADE, db_column='iduserposcheck', null=True, blank=True, related_name='poscheck_texts')

    class Meta:
        db_table = 'tbltext'

    def __str__(self):
        return self.header

class TextType(models.Model):
    idtexttype = models.AutoField(primary_key=True)
    texttypename = models.CharField(max_length=100, unique=True)

    class Meta:
        db_table = 'tbltexttype'

    def __str__(self):
        return self.texttypename

class Token(models.Model):
    idtoken = models.AutoField(primary_key=True)
    tokentext = models.TextField()  # longtext соответствует TextField
    tokenordernumber = models.IntegerField()
    idsentence = models.ForeignKey(Sentence, on_delete=models.CASCADE, related_name='tokens', db_column='idsentence')  # Используем существующую колонку
    idpostag = models.ForeignKey(PosTag, on_delete=models.CASCADE, null=True, blank=True, db_column='idpostag')  # Используем существующую колонку

    class Meta:
        db_table = 'tbltoken'
        indexes = [
            models.Index(fields=['idsentence']),
            models.Index(fields=['idpostag']),
        ]

    def __str__(self):
        return f"Token {self.idtoken}: {self.tokentext}"


class WritePlace(models.Model):
    idwriteplace = models.AutoField(primary_key=True)
    writeplacename = models.CharField(max_length=100, unique=True)

    class Meta:
        db_table = 'tblwriteplace'

    def __str__(self):
        return self.writeplacename
    
class WriteTool(models.Model):
    idwritetool = models.AutoField(primary_key=True)
    writetoolname = models.CharField(max_length=100, unique=True)

    class Meta:
        db_table = 'tblwritetool'

    def __str__(self):
        return self.writetoolname

text_app/models.py
from django.db import models

# Create your models here.

text_app/templates/text_app/home.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная страница</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <div class="container">
        <a href="{% url 'show_text_markup' %}" class="btn">Перейти к разметке текста</a>
    </div>
</body>
</html>

text_app/templates/text_app/show_error_markup.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Разметка ошибок</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/text_markup.css' %}" />
</head>
<body>

    <!-- Всплывающее окно -->
    <div class="error-popup" id="error-popup">
        <span class="close-btn" id="close-popup">X</span>
        <h3>
            <span id="error-tag"></span>
            <span id="error-tag-abbrev"></span>
        </h3>
        <p><strong>Степень грубости:</strong> <span id="error-level"></span></p>
        <p><strong>Исправление:</strong> <span id="error-correct"></span></p>
        <p><strong>Комментарий:</strong> <span id="error-comment"></span></p>
    </div>

    <div class="menu">
        <form method="get" action="">
            <label for="markup">Вид:</label>
            <select name="markup" id="markup" onchange="this.form.submit();">
                <option value="tagtext" {% if selected_markup == 'tagtext' %}selected{% endif %}>Ошибки (Основная)</option>
                <option value="tagtextrussian" {% if selected_markup == 'tagtextrussian' %}selected{% endif %}>Ошибки (На русском)</option>
                <option value="tagtextabbrev" {% if selected_markup == 'tagtextabbrev' %}selected{% endif %}>Аббревиатуры ошибок</option>
                <option value="plain" {% if selected_markup == 'plain' %}selected{% endif %}>Без разметки</option>
            </select>
        </form>
    </div>
    
    <div class="text-header">
        <h1 class="text-title">{{ text.header }}</h1>
    </div>

    <div class="watch-text">
        {% for sentence in text.sentence_set.all %}
            <div class="sentence">
                <p class="sentence-number">{{ forloop.counter }}:</p>
                <div class="tokens-container">
                    {% for token in token_data %}
                        <span class="token" 
                            {% if token.error_tag %}
                                data-error-tag="{{ token.error_tag }}" 
                                data-error-tag-abbrev="{{ token.error_tag_abbrev }}" 
                                data-error-level="{{ token.error_level }}" 
                                data-error-correct="{{ token.error_correct }}" 
                                data-error-comment="{{ token.error_comment }}" 
                                data-error-color="{{ token.error_color }}"
                            {% endif %}
                        >
                            {% if token.error_tag %}
                                <span class="error-tag" style="background-color: {{ token.error_color }};">
                                    {{ token.error_tag }}
                                </span>
                            {% else %}
                                <span class="no-abbr">&nbsp;</span>
                            {% endif %}
                            <span class="word">{{ token.token }}</span>
                        </span>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const markupSelect = document.getElementById('markup');
            const popup = document.getElementById('error-popup');
            const closePopupBtn = document.getElementById('close-popup');
    
            // Функция для отображения всплывающего окна с информацией об ошибке
            function showPopup(tokenElement) {
                const errorTag = tokenElement.dataset.errorTag;
                const errorTagAbbrev = tokenElement.dataset.errorTagAbbrev;
                const errorLevel = tokenElement.dataset.errorLevel;
                const errorCorrect = tokenElement.dataset.errorCorrect;
                const errorComment = tokenElement.dataset.errorComment;
    
                // Проверяем, есть ли ошибка у токена
                if (!errorTag) {
                    return; // Если ошибки нет, ничего не делаем
                }
    
                document.getElementById('error-tag').textContent = errorTag || 'Не указано';
                document.getElementById('error-tag-abbrev').textContent = errorTagAbbrev ? `(${errorTagAbbrev})` : '';
                document.getElementById('error-level').textContent = errorLevel || 'Не указано';
                document.getElementById('error-correct').textContent = errorCorrect || 'Не указано';
                document.getElementById('error-comment').textContent = errorComment || 'Не указано';
    
                // Получаем позицию токена на странице
                const tokenRect = tokenElement.getBoundingClientRect();

                var rect = tokenElement.getBoundingClientRect();
                var offsetLeft = rect.left + window.scrollX;
                var offsetTop = rect.top + window.scrollY;
                var height = rect.height;
                var width = rect.width;
                var left = offsetLeft ;
                var top = offsetTop - height - 6;
               // Устанавливаем ширину всплывающего окна равной ширине токена
                popup.style.width = `${tokenRect.width}px`;
                popup.style.left = left + 'px';
                popup.style.top = top + 'px';

                // const tokenRect = tokenElement.getBoundingClientRect();
                // const popup = document.getElementById('error-popup');

                // // Устанавливаем ширину всплывающего окна равной ширине токена
                // popup.style.width = `${tokenRect.width}px`;

                // const viewportHeight = window.innerHeight; // Высота окна просмотра
                // let top = tokenRect.top - popup.offsetHeight - 6; // Позиция над токеном

                // // Проверяем, вмещается ли всплывающее окно над токеном
                // if (top < 0 || (tokenRect.top - popup.offsetHeight) < 0) {
                //     top = tokenRect.bottom + 6; // Если нет, позиционируем под токеном
                // }

                // popup.style.left = `${tokenRect.left}px`;
                // popup.style.top = `${top}px`;

                
    
                // Позиционируем всплывающее окно над токеном
               // popup.style.left = `${tokenRect.left}px`;
               // popup.style.top = `${tokenRect.top - popup.offsetHeight - 10}px`; // Сдвигаем окно вверх
    
                popup.style.display = 'block';
                popup.classList.add('show'); // Добавляем класс для анимации
            }

            // Закрытие окна с анимацией
            closePopupBtn.addEventListener('click', function() {
                const popup = document.getElementById('error-popup');
                popup.classList.remove('show'); // Убираем класс для анимации исчезновения
                setTimeout(() => {
                    popup.style.display = 'none'; // Скрываем окно после анимации
                }, 300); // Задержка, соответствующая длительности перехода
            });
    
            // Закрыть всплывающее окно
            closePopupBtn.addEventListener('click', function() {
                popup.style.display = 'none';
            });
    
            // Слушаем клик по токенам
            document.querySelectorAll('.token').forEach(function(tokenElement) {
                tokenElement.addEventListener('click', function() {
                    // Показываем всплывающее окно с информацией об ошибке, если она есть
                    showPopup(tokenElement);
                });
            });
    
            // Функция для переключения видимости тегов ошибок
            function toggleErrorTagVisibility() {
                const errorTagElements = document.querySelectorAll('.error-tag');
                if (markupSelect.value === 'plain') {
                    errorTagElements.forEach(el => el.style.display = 'none');
                } else {
                    errorTagElements.forEach(el => el.style.display = 'flex');
                }
            }
    
            // Вызвать функцию при загрузке страницы
            toggleErrorTagVisibility();
    
            // Добавить слушатель для изменения значения в селекте
            markupSelect.addEventListener('change', toggleErrorTagVisibility);
        });
    </script>

</body>
</html>

text_app/templates/text_app/show_text.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Разметка текста</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/text_markup.css' %}" />
</head>
<body>

    <div class="menu">
        <form method="get" action="">
            <label for="markup">Вид:</label>
            <select name="markup" id="markup" onchange="this.form.submit();">
                <option value="tagtext" {% if selected_markup == 'tagtext' %}selected{% endif %}>Части речи (Основная)</option>
                <option value="tagtextrussian" {% if selected_markup == 'tagtextrussian' %}selected{% endif %}>Части речи (На русском)</option>
                <option value="tagtextabbrev" {% if selected_markup == 'tagtextabbrev' %}selected{% endif %}>Аббревиатуры части речи</option>
                <option value="plain" {% if selected_markup == 'plain' %}selected{% endif %}>Без разметки</option>
            </select>
        </form>
    </div>
    
    <div class="text-header">
        <h1 class="text-title">{{ text.header }}</h1>
    </div>

    <div class="watch-text">
        {% for sentence in text.sentence_set.all %}
            <div class="sentence">
                <p class="sentence-number">{{ forloop.counter }}:</p>
                <div class="tokens-container">
                {% for token in sentence.tokens.all %}
                    <span class="token">
                        
                        {% if token.idpostag %}
                            <span class="abbr" style="background-color: {{ token.idpostag.tagcolor }};">
                                {% if selected_markup == 'tagtext' %}
                                    {{ token.idpostag.tagtext }}
                                {% elif selected_markup == 'tagtextrussian' %}
                                    {{ token.idpostag.tagtextrussian }}
                                {% elif selected_markup == 'tagtextabbrev' %}
                                    {{ token.idpostag.tagtextabbrev }}
                                {% endif %}
                            </span>
                        {% elif selected_markup != 'plain' %}
                            <span class="no-abbr">&nbsp;</span> 
                        {% endif %}

                            <span class="word">{{ token.tokentext }}</span>

                    </span>
                {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>

    
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const markupSelect = document.getElementById('markup');

            function toggleAbbrVisibility() {
                const abbrElements = document.querySelectorAll('.abbr');
                if (markupSelect.value === 'plain') {
                    abbrElements.forEach(el => el.style.display = 'none');
                } else {
                    abbrElements.forEach(el => el.style.display = 'flex');
                }
            }

            // Вызвать функцию при загрузке страницы
            toggleAbbrVisibility();

            // Добавить слушатель для изменения значения в селекте
            markupSelect.addEventListener('change', toggleAbbrVisibility);
        });
    </script>


</body>
</html>